# Generated by Django 4.2.3 on 2023-08-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_favoriteproduct_product_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorites',
        ),
    ]
