# Generated by Django 4.2.3 on 2023-08-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='favorite_products',
        ),
    ]
